### ISSUE TITLE
Event stream error: {"type":"error"}

### ISSUE THREAD

**Issue by seagull9000** [Alainx277/node-red-miele#2]
First time connection, completed configuration.  The node found the dryer I have, but output to debug repeats the message:

Event stream error: {"type":"error"}

every 2 seconds

**Comment by seagull9000** [comment]
Solved.  For the interest of others who may get this error, there were two issues:

1.  I had to allow the app read access to the device through the Miele API portal, even though it seemed to find my device without this step.
2. I had to restart nodered (not sure if this was due to me mucking about trying to get things to work or not).

I would suggest updating the guide with the step required to fix 1.  The guide says further instructions are available through nodered help, but I could not find these.

Good module.  Very useful.

**Comment by RadianM** [comment]
> Solved. For the interest of others who may get this error, there were two issues:
> 
> 1. I had to allow the app read access to the device through the Miele API portal, even though it seemed to find my device without this step.
> 2. I had to restart nodered (not sure if this was due to me mucking about trying to get things to work or not).
> 
> I would suggest updating the guide with the step required to fix 1. The guide says further instructions are available through nodered help, but I could not find these.
> 
> Good module. Very useful.

When you say you allowed the app read access to the device through the Miele API portal, how's that done? 
[https://www.miele.com/developer/swagger-ui/](https://www.miele.com/developer/swagger-ui/) lets you enter credentials in order to try various API calls from their website but the authorisation here doesn't bear any relation to node-red.

The Miele appliances broadcast their IDs on the local network so maybe that's how it seemed to find your device. I take it this appeared in a dropdown menu in the credentials panel in node-red? I don't even get that. My IDs are empty.
